name: halcyon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audiotags: ^1.3.0
  discord_rpc: ^0.0.2
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_soloud: ^2.0.0
  mason_logger: ^0.2.12
  multi_split_view: ^2.4.0
  provider: ^6.1.2
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
